# Generated by Django 4.0.6 on 2022-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image_user_tab_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tab_number',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
