# Generated by Django 4.0.6 on 2022-07-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_company_logo_alter_items_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel',
            new_name='user',
        ),
    ]
