# Generated by Django 4.0.6 on 2022-07-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_hotel_general_manager_alter_hotel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='disc_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
