# Generated by Django 4.0.6 on 2022-07-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='company',
        ),
        migrations.AddField(
            model_name='items',
            name='is_quick_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.hotel'),
        ),
    ]
