# Generated by Django 4.0.6 on 2022-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_menu_company_items_is_quick_link_menu_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
