# Generated by Django 4.0.6 on 2022-08-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_items_disc_price_alter_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.hotel'),
        ),
    ]
