# Generated by Django 4.0.6 on 2022-08-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_items_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.hotel'),
        ),
    ]
